dist: trusty
sudo: required

language: node_js

node_js:
  - 'node'

cache:
  yarn: true
  directories:
    - ./node_modules
    - $HOME/.cache/yarn
    - $HOME/.npm

matrix:
  fast_finish: true

install:
  - yarn

script:
  - yarn lint
  - yarn prod

before_deploy:
  - yarn prod

deploy:
  provider: pages
  local-dir: ./dist/
  skip-cleanup: false
  github-token: $GH_TOKEN
  keep-history: false
  verbose: true
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: change
