language: node_js

node_js:
  - 10.15.1

cache:
  yarn: true
  directories:
    - ./node_modules
    - $HOME/.cache/yarn
    - $HOME/.npm

matrix:
  fast_finish: true

install:
  - yarn

script:
  - yarn lint
  - yarn prod

notifications:
  email:
    on_success: never
    on_failure: change
